In [1]:
#question 4
#construction of the matrix
# a 3x3 matrix as a numpy array

import numpy as np
import math

my_matrix = np.array([[1, 0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(my_matrix)

#(a)
#inversing the matrix
inverse=np.linalg.inv(my_matrix)
print(inverse)


#(b)
#determinant of the above matrix
determinat=np.linalg.det(my_matrix)
print(f' the deternimant is {determinat}')

# #(c)
# #decomposing the matrix
# decom=np.dot(my_matrix)
# print(decom)

#(e)
#transforming the matrix



[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]
 the deternimant is 0.2299999999999999


In [3]:
#question 5
#python program solving any 3 linear equations using matrices
# 2 solving 2x + 5y =10 2x + 6y=9
import numpy as np

w=np.array([[2,5],[2,6]])
z=np.array([10,9])
soln=np.linalg.solve(w,z)
print(soln)


[ 7.5 -1. ]
